Add extra link to migration.md
nats-io/nats.js pull request #167
Opened 2024-12-05 22:39 UTC by alexbozhenko

[ci skip]

2024-12-06 01:52 UTC, aricart requested changes
can you run `deno fmt` in the project - you may need to install deno.

2024-12-06 03:36 UTC, alexbozhenko commented
@aricart isn't it(https://docs.deno.com/runtime/reference/cli/fmt/) for formatting javascript files?
I only changed markdown here.

2024-12-06 04:56 UTC, aricart commented
Yes it will format the markdown too

2024-12-09 16:46 UTC, aricart approved these changes

2024-12-09 16:46 UTC, merged